### PR TITLE
Removing Duplicates from LL

### PR DESCRIPTION
**Pull request by Shalavya8103**
Removinfg Duplicates from Linked List

### CODE REVIEW

**Review by ShehrozIrfan — CHANGES_REQUESTED** [review]
Good Work.
Just a suggestion, please also add the code to implement this, like taking input from user and creating a linked list and then remove the duplicates by calling the method you added.

**Comment by Shalavya8103** [comment]
Changes made and new pull request made

**Comment by Shalavya8103** [comment]
Thanks for suggestion,  the necessary changes made

**Review by ShehrozIrfan — APPROVED** [review]
Perfect.

Screenshot 2023-10-06 at 9 53 00 AM

**Comment by ShehrozIrfan** [comment]
@Shalavya8103 
Great work 💯
Contribution accepted 🚀

You can follow me and star this repo for further updates.
Have fun

**Pull request merged**
